#include "SweepFeature.h"

#include <BRepOffsetAPI_MakePipe.hxx>
#include <BRepOffsetAPI_MakePipeShell.hxx>
#include <ShapeAnalysis_FreeBounds.hxx>
#include <TopTools_HSequenceOfShape.hxx>
#include <BRep_Tool.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeWire.hxx>
#include <BRepAlgoAPI_Fuse.hxx>
#include <BRepAlgoAPI_Cut.hxx>
#include <BRepAlgoAPI_Common.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepTools.hxx>
#include <gp_Dir.hxx>
#include <GC_MakeArcOfCircle.hxx>
#include <Geom_TrimmedCurve.hxx>
#include <TopExp.hxx>

#include <iostream>
#include <cmath>

namespace CADEngine {

SweepFeature::SweepFeature(const std::string& name)
    : Feature(FeatureType::Unknown, name)
{
    setInt("operation", static_cast<int>(ExtrudeOperation::NewBody));
}

void SweepFeature::setProfileSketch(std::shared_ptr<SketchFeature> sketch) {
    m_profileSketch = sketch;
    if (sketch) addDependency(sketch->getId());
}

void SweepFeature::setPathSketch(std::shared_ptr<SketchFeature> sketch) {
    m_pathSketch = sketch;
    if (sketch) addDependency(sketch->getId());
}

void SweepFeature::setOperation(ExtrudeOperation op) {
    setInt("operation", static_cast<int>(op));
    invalidate();
}

void SweepFeature::setExistingBody(const TopoDS_Shape& body) {
    m_existingBody = body;
}

void SweepFeature::setProfileFace(const TopoDS_Face& face) {
    m_profileFace = face;
}

void SweepFeature::setPathWire(const TopoDS_Wire& wire) {
    m_pathWire = wire;
}

ExtrudeOperation SweepFeature::getOperation() const {
    return static_cast<ExtrudeOperation>(getInt("operation"));
}

TopoDS_Face SweepFeature::buildProfileFace() const {
    if (!m_profileFace.IsNull()) return m_profileFace;
    if (!m_profileSketch || !m_profileSketch->getSketch2D()) return TopoDS_Face();

    auto sketch2D = m_profileSketch->getSketch2D();
    auto regions = sketch2D->buildFaceRegions();
    if (regions.empty()) {
        std::cerr << "[Sweep] Profile sketch has no closed region" << std::endl;
        return TopoDS_Face();
    }
    return regions[0].face;
}

TopoDS_Wire SweepFeature::buildProfileWire() const {
    if (!m_profileSketch || !m_profileSketch->getSketch2D()) return TopoDS_Wire();
    auto sketch2D = m_profileSketch->getSketch2D();
    auto regions = sketch2D->buildFaceRegions();
    if (!regions.empty() && !regions[0].face.IsNull()) {
        TopoDS_Wire w = BRepTools::OuterWire(regions[0].face);
        if (!w.IsNull()) return w;
    }
    // fallback : reconstruire depuis les arêtes
    auto edges = sketch2D->getEdges3D();
    BRepBuilderAPI_MakeWire wm;
    for (const auto& e : edges)
        if (!e.IsNull()) wm.Add(e);
    if (wm.IsDone()) return wm.Wire();
    return TopoDS_Wire();
}

// Detect sequences of consecutive short straight edges that approximate a circular arc
// (generated by onFilletVertex) and replace them with a single proper OCCT arc edge.
// This prevents MakePipeShell from creating many small transition faces at fillet corners.
static std::vector<TopoDS_Edge> mergeArcSequences(const std::vector<TopoDS_Edge>& edges) {
    int n = (int)edges.size();
    if (n < 3) return edges;

    // Collect start/end points for all edges (respects edge orientation via TopExp::Vertices)
    auto getEndPnt = [](const TopoDS_Edge& e, bool atStart) -> gp_Pnt {
        TopoDS_Vertex vFirst, vLast;
        TopExp::Vertices(e, vFirst, vLast);
        if (atStart) return BRep_Tool::Pnt(vFirst);
        return BRep_Tool::Pnt(vLast);
    };

    std::vector<gp_Pnt> pts(n + 1);
    pts[0] = getEndPnt(edges[0], true);
    for (int i = 0; i < n; i++)
        pts[i + 1] = getEndPnt(edges[i], false);

    // Unit direction vectors
    std::vector<gp_Vec> dirs(n);
    std::vector<double> lens(n);
    for (int i = 0; i < n; i++) {
        dirs[i] = gp_Vec(pts[i], pts[i + 1]);
        lens[i] = dirs[i].Magnitude();
        if (lens[i] > 1e-10) dirs[i] /= lens[i];
    }

    // Turn angle magnitude at vertex between edge i-1 and edge i
    auto turnMag = [&](int i) -> double {
        if (i <= 0 || i >= n) return 0.0;
        double cosA = std::max(-1.0, std::min(1.0, dirs[i-1].Dot(dirs[i])));
        return std::acos(cosA);
    };

    // Cross product (rotation axis) at vertex between edge i-1 and edge i
    auto crossVec = [&](int i) -> gp_Vec {
        if (i <= 0 || i >= n) return gp_Vec(0,0,1);
        return dirs[i-1].Crossed(dirs[i]);
    };

    std::vector<TopoDS_Edge> result;
    int i = 0;
    while (i < n) {
        if (i + 2 >= n) {
            result.push_back(edges[i]);
            i++;
            continue;
        }

        double firstTurn = turnMag(i + 1);
        // Only detect fillet arc segments: > ~3° and < ~23° per segment.
        // onFilletVertex generates at most 10° per segment (max angle / arcSegments).
        // Sharp polyline corners (e.g. 90°) must NOT be detected as arcs.
        if (firstTurn < 0.05 || firstTurn > 0.42) {
            result.push_back(edges[i]);
            i++;
            continue;
        }

        gp_Vec firstCross = crossVec(i + 1);
        double firstCrossMag = firstCross.Magnitude();
        if (firstCrossMag < 1e-10) {
            result.push_back(edges[i]);
            i++;
            continue;
        }
        firstCross /= firstCrossMag;

        // Extend arc sequence as long as turn angles and rotation axes are consistent
        int arcLast = i + 1;
        while (arcLast + 1 < n) {
            double nextTurn = turnMag(arcLast + 1);
            gp_Vec nextCross = crossVec(arcLast + 1);
            double ncm = nextCross.Magnitude();
            if (ncm > 1e-10) nextCross /= ncm;

            bool sameTurn = (std::abs(nextTurn - firstTurn) < 0.30 * firstTurn);
            bool sameAxis = (ncm > 1e-10 && firstCross.Dot(nextCross) > 0.7);
            bool similarLen = (lens[i] > 1e-10 &&
                               lens[arcLast + 1] / lens[i] > 0.3 &&
                               lens[arcLast + 1] / lens[i] < 3.0);

            if (sameTurn && sameAxis && similarLen)
                arcLast++;
            else
                break;
        }

        int arcLen = arcLast - i + 1;
        if (arcLen < 3) {
            result.push_back(edges[i]);
            i++;
            continue;
        }

        // Build a single arc edge from arcStart → arcMid → arcEnd
        gp_Pnt arcP1 = pts[i];
        gp_Pnt arcP2 = pts[i + arcLen / 2];
        gp_Pnt arcP3 = pts[i + arcLen];

        bool merged = false;
        if (arcP1.Distance(arcP2) > 1e-6 && arcP2.Distance(arcP3) > 1e-6 &&
            arcP1.Distance(arcP3) > 1e-6) {
            try {
                GC_MakeArcOfCircle arcMaker(arcP1, arcP2, arcP3);
                if (arcMaker.IsDone()) {
                    BRepBuilderAPI_MakeEdge em(arcMaker.Value());
                    if (em.IsDone()) {
                        result.push_back(em.Edge());
                        std::cout << "[Sweep] Merged " << arcLen
                                  << " edges into arc (total turn "
                                  << (arcLen * firstTurn * 180.0 / M_PI) << "°)" << std::endl;
                        i = arcLast + 1;
                        merged = true;
                    }
                }
            } catch (...) {}
        }

        if (!merged) {
            for (int j = i; j <= arcLast; j++)
                result.push_back(edges[j]);
            i = arcLast + 1;
        }
    }
    return result;
}

TopoDS_Wire SweepFeature::buildPathWire() const {
    if (!m_pathWire.IsNull()) return m_pathWire;
    if (!m_pathSketch || !m_pathSketch->getSketch2D()) return TopoDS_Wire();

    auto sketch2D = m_pathSketch->getSketch2D();
    auto entities = sketch2D->getEntities();
    gp_Pln plane = sketch2D->getPlane();

    // Collecter toutes les arêtes réelles (hors construction)
    Handle(TopTools_HSequenceOfShape) edgeSeq = new TopTools_HSequenceOfShape();
    int edgeCount = 0;

    for (const auto& entity : entities) {
        if (!entity || !entity->isValid() || entity->isConstruction()) continue;
        auto edges = entity->toEdges3D(plane);
        for (const auto& edge : edges) {
            if (!edge.IsNull()) {
                edgeSeq->Append(edge);
                edgeCount++;
            }
        }
    }

    std::cout << "[Sweep] Path wire: " << edgeCount << " real edge(s)" << std::endl;

    if (edgeCount == 0) {
        std::cerr << "[Sweep] ERROR: Path sketch has no usable entities" << std::endl;
        return TopoDS_Wire();
    }

    // Collecte des arêtes dans un vecteur pour le tri topologique
    std::vector<TopoDS_Edge> pool;
    for (int i = 1; i <= edgeSeq->Length(); i++)
        pool.push_back(TopoDS::Edge(edgeSeq->Value(i)));

    // Tri topologique : on chaîne les arêtes en cherchant à chaque étape
    // l'arête dont un endpoint coïncide avec la fin courante du wire.
    // TopExp::Vertices respecte l'orientation de l'arête (contrairement à TopExp_Explorer).
    auto edgeStart = [](const TopoDS_Edge& e) -> gp_Pnt {
        TopoDS_Vertex vFirst, vLast;
        TopExp::Vertices(e, vFirst, vLast);
        return BRep_Tool::Pnt(vFirst);
    };
    auto edgeEnd = [](const TopoDS_Edge& e) -> gp_Pnt {
        TopoDS_Vertex vFirst, vLast;
        TopExp::Vertices(e, vFirst, vLast);
        return BRep_Tool::Pnt(vLast);
    };

    const double matchTol = 1.0; // tolérance de connexion en mm

    std::vector<TopoDS_Edge> ordered;
    std::vector<bool> used(pool.size(), false);

    // Démarrer avec la première arête
    ordered.push_back(pool[0]);
    used[0] = true;
    gp_Pnt currentEnd = edgeEnd(pool[0]);

    while (ordered.size() < pool.size()) {
        bool found = false;
        for (size_t i = 0; i < pool.size(); i++) {
            if (used[i]) continue;
            gp_Pnt s = edgeStart(pool[i]);
            gp_Pnt e = edgeEnd(pool[i]);
            if (currentEnd.Distance(s) < matchTol) {
                // Arête en avant
                ordered.push_back(pool[i]);
                used[i] = true;
                currentEnd = e;
                found = true;
                break;
            } else if (currentEnd.Distance(e) < matchTol) {
                // Arête à inverser
                TopoDS_Edge rev = TopoDS::Edge(pool[i].Reversed());
                ordered.push_back(rev);
                used[i] = true;
                currentEnd = s;
                found = true;
                break;
            }
        }
        if (!found) {
            std::cerr << "[Sweep] WARNING: Path wire has gap, stopping at " << ordered.size() << " edges" << std::endl;
            break;
        }
    }

    // Merge arc-approximated polyline fillet segments into proper OCCT arc edges
    // to avoid many small faces at rounded corners when using MakePipeShell
    int edgesBefore = (int)ordered.size();
    ordered = mergeArcSequences(ordered);
    if ((int)ordered.size() < edgesBefore)
        std::cout << "[Sweep] Arc merge: " << edgesBefore << " → " << ordered.size() << " edges" << std::endl;

    // Sharp-corner detection: inspect tangents at each junction of the ordered edges.
    // We do this BEFORE BRepBuilderAPI_MakeWire because the wire builder may share
    // vertices, retag orientations, or otherwise reshape the topology in ways that
    // mask the original geometry. Working directly on `ordered` is the source of truth.
    //
    // For a chamfered polyline path (45° miters), consecutive line segments meet at
    // ~45° → angle well above tolerance → sharp corner detected.
    // For a filleted path (arc tangent to lines), the arc is tangent at its endpoints
    // → angle near zero → no sharp corner.
    m_pathHasSharpCorners = false;
    {
        const double angleTolRad = 0.05;  // ~2.9°, safe margin against numerical noise

        auto tangentForward = [](const TopoDS_Edge& e, bool atEnd) -> gp_Vec {
            // Tangent in the wire's traversal direction at start/end of this edge.
            // Respects edge orientation: a REVERSED edge is walked from l→f, and the
            // raw curve tangent must be reversed.
            Standard_Real f = 0.0, l = 0.0;
            Handle(Geom_Curve) c = BRep_Tool::Curve(e, f, l);
            if (c.IsNull()) return gp_Vec(0, 0, 0);
            const bool reversed = (e.Orientation() == TopAbs_REVERSED);
            const Standard_Real param = atEnd ? (reversed ? f : l) : (reversed ? l : f);
            gp_Pnt p; gp_Vec t;
            try { c->D1(param, p, t); } catch (...) { return gp_Vec(0, 0, 0); }
            if (reversed) t.Reverse();
            return t;
        };

        std::cout << "[Sweep] Inspecting " << ordered.size() << " path edges for sharp corners..." << std::endl;
        for (size_t k = 0; k + 1 < ordered.size(); k++) {
            gp_Vec t1 = tangentForward(ordered[k],     true);
            gp_Vec t2 = tangentForward(ordered[k + 1], false);
            double m1 = t1.Magnitude(), m2 = t2.Magnitude();
            if (m1 < 1e-10 || m2 < 1e-10) {
                std::cout << "  junction " << k << ": degenerate tangent (|t1|=" << m1
                          << " |t2|=" << m2 << "), skipping" << std::endl;
                continue;
            }
            t1 /= m1; t2 /= m2;
            double cosA = t1.Dot(t2);
            if (cosA >  1.0) cosA =  1.0;
            if (cosA < -1.0) cosA = -1.0;
            double angle = std::acos(cosA);
            std::cout << "  junction " << k << ": "
                      << "t1=(" << t1.X() << "," << t1.Y() << "," << t1.Z() << ") "
                      << "t2=(" << t2.X() << "," << t2.Y() << "," << t2.Z() << ") "
                      << "angle=" << (angle * 180.0 / M_PI) << "°"
                      << ((angle > angleTolRad) ? "  ← SHARP" : "") << std::endl;
            if (angle > angleTolRad) m_pathHasSharpCorners = true;
        }
        std::cout << "[Sweep] Path has sharp corners: " << (m_pathHasSharpCorners ? "YES" : "no") << std::endl;
    }

    BRepBuilderAPI_MakeWire wireBuilder;
    for (const auto& e : ordered)
        wireBuilder.Add(e);

    if (wireBuilder.IsDone()) {
        std::cout << "[Sweep] Path wire: built with topological sort (" << ordered.size() << " edges)" << std::endl;
        return wireBuilder.Wire();
    }

    std::cerr << "[Sweep] ERROR: Path wire build failed after topological sort" << std::endl;
    return TopoDS_Wire();
}

bool SweepFeature::compute() {
    std::cout << "[Sweep] Computing..." << std::endl;

    TopoDS_Face profile = buildProfileFace();
    if (profile.IsNull()) {
        std::cerr << "[Sweep] ERROR: No profile face — profile sketch must be a closed shape" << std::endl;
        return false;
    }

    TopoDS_Wire path = buildPathWire();
    if (path.IsNull()) {
        std::cerr << "[Sweep] ERROR: No path wire" << std::endl;
        return false;
    }

    // Vérifier que profil et chemin ne sont pas sur le même plan (pipe dégénéré)
    if (m_profileSketch && m_pathSketch &&
        m_profileSketch->getSketch2D() && m_pathSketch->getSketch2D())
    {
        gp_Dir profileNormal = m_profileSketch->getSketch2D()->getPlane().Axis().Direction();
        gp_Dir pathNormal    = m_pathSketch->getSketch2D()->getPlane().Axis().Direction();
        if (profileNormal.IsParallel(pathNormal, 0.01)) {
            std::cerr << "[Sweep] ERROR: Profile and path sketches are on parallel planes — "
                         "use perpendicular planes (e.g. profile on XY, path on XZ)" << std::endl;
            return false;
        }
    }

    try {
        TopoDS_Shape sweepShape;
        bool sweepShapeOK = false;

        TopoDS_Wire profileWire = buildProfileWire();

        // Path plane normal — used as the constant binormal direction for the trihedron
        // when the path is planar (which is the common case: path comes from a 2D sketch).
        // ConstantBinormal mode keeps the swept profile perpendicular to the path's plane
        // along the whole spine, eliminating profile twist on arcs (filleted corners).
        // DiscreteMode remains as fallback for 3D paths set via setPathWire().
        bool havePathPlane = false;
        gp_Dir pathPlaneNormal(0, 0, 1);
        if (m_pathSketch && m_pathSketch->getSketch2D()) {
            pathPlaneNormal = m_pathSketch->getSketch2D()->getPlane().Axis().Direction();
            havePathPlane = true;
            std::cout << "[Sweep] Path plane normal: ("
                      << pathPlaneNormal.X() << "," << pathPlaneNormal.Y() << "," << pathPlaneNormal.Z()
                      << ") — using ConstantBinormal trihedron" << std::endl;
        } else {
            std::cout << "[Sweep] No path plane (3D wire) — using DiscreteMode trihedron" << std::endl;
        }

        // Helper: try MakePipeShell with a given transition mode. On success, fills
        // sweepShape and returns true. On any kind of failure (not ready, build
        // failed, raised exception) returns false and leaves sweepShape untouched.
        auto tryPipeShell = [&](BRepBuilderAPI_TransitionMode mode, const char* label) -> bool {
            if (profileWire.IsNull()) return false;
            try {
                BRepOffsetAPI_MakePipeShell pipeShell(path);
                pipeShell.SetTransitionMode(mode);

                // Trihedron / spine mode (MUST be set before Add()).
                //   Planar path  → SetMode(BiNormal) with the path plane normal :
                //                  binormale constante, aucune rotation du profil
                //                  autour de la tangente. Mathématiquement exact pour
                //                  un sketch 2D, élimine le twist sur les arcs.
                //   3D path      → SetDiscreteMode (calcul local du repère)
                if (havePathPlane) {
                    pipeShell.SetMode(pathPlaneNormal);
                } else {
                    pipeShell.SetDiscreteMode();
                }

                pipeShell.Add(profileWire, Standard_False, Standard_True);

                std::cout << "[Sweep] Trying " << label
                          << " — IsReady: " << pipeShell.IsReady() << std::endl;
                if (!pipeShell.IsReady()) return false;
                pipeShell.Build();
                std::cout << "[Sweep] " << label
                          << " — IsDone: " << pipeShell.IsDone()
                          << "  ErrorOnSurface: " << pipeShell.ErrorOnSurface() << std::endl;
                if (!pipeShell.IsDone()) return false;
                pipeShell.MakeSolid();
                sweepShape = pipeShell.Shape();
                std::cout << "[Sweep] MakePipeShell (" << label << "): OK" << std::endl;
                return true;
            } catch (Standard_Failure& e) {
                std::cerr << "[Sweep] MakePipeShell (" << label << ") raised: "
                          << e.GetMessageString() << std::endl;
                return false;
            }
        };

        // Pick preferred mode from path geometry, with the other mode as fallback.
        // Sharp-cornered path (chanfreins, polylignes vives) → RightCorner (mitered).
        // Tangent-continuous path (congés)                   → Transformed (no extra face).
        BRepBuilderAPI_TransitionMode preferred =
            m_pathHasSharpCorners ? BRepBuilderAPI_RightCorner : BRepBuilderAPI_Transformed;
        BRepBuilderAPI_TransitionMode fallback =
            m_pathHasSharpCorners ? BRepBuilderAPI_Transformed : BRepBuilderAPI_RightCorner;
        const char* preferredLabel = m_pathHasSharpCorners ? "RightCorner" : "Transformed";
        const char* fallbackLabel  = m_pathHasSharpCorners ? "Transformed" : "RightCorner";

        std::cout << "[Sweep] Preferred transition mode: " << preferredLabel
                  << " (sharp corners: " << (m_pathHasSharpCorners ? "yes" : "no") << ")" << std::endl;

        sweepShapeOK = tryPipeShell(preferred, preferredLabel);
        if (!sweepShapeOK) {
            std::cout << "[Sweep] Preferred mode failed, trying fallback: " << fallbackLabel << std::endl;
            sweepShapeOK = tryPipeShell(fallback, fallbackLabel);
        }

        // Final fallback: classical MakePipe (no transition mode control)
        if (!sweepShapeOK) {
            std::cout << "[Sweep] PipeShell failed both modes, falling back to MakePipe" << std::endl;
            BRepOffsetAPI_MakePipe pipe(path, profile);
            pipe.Build();
            if (!pipe.IsDone()) {
                std::cerr << "[Sweep] ERROR: MakePipe also failed" << std::endl;
                return false;
            }
            sweepShape = pipe.Shape();
            sweepShapeOK = true;
            std::cout << "[Sweep] MakePipe (final fallback): OK" << std::endl;
        }

        ExtrudeOperation op = getOperation();
        if (op == ExtrudeOperation::NewBody || m_existingBody.IsNull()) {
            m_resultShape = sweepShape;
            m_shape = sweepShape;
        } else if (op == ExtrudeOperation::Join) {
            BRepAlgoAPI_Fuse fuse(m_existingBody, sweepShape);
            if (fuse.IsDone()) { m_resultShape = fuse.Shape(); m_shape = m_resultShape; }
            else { m_resultShape = sweepShape; m_shape = sweepShape; }
        } else if (op == ExtrudeOperation::Cut) {
            BRepAlgoAPI_Cut cut(m_existingBody, sweepShape);
            if (cut.IsDone()) { m_resultShape = cut.Shape(); m_shape = m_resultShape; }
            else return false;
        } else if (op == ExtrudeOperation::Intersect) {
            BRepAlgoAPI_Common common(m_existingBody, sweepShape);
            if (common.IsDone()) { m_resultShape = common.Shape(); m_shape = m_resultShape; }
            else return false;
        }

        m_upToDate = true;
        std::cout << "[Sweep] Success" << std::endl;
        return true;

    } catch (Standard_Failure& e) {
        std::cerr << "[Sweep] OCCT Exception: " << e.GetMessageString() << std::endl;
        return false;
    }
}

} // namespace CADEngine
